### ISSUE TITLE
Image Size Problem

### ISSUE THREAD

**Issue by r05922121** [jwyang/JULE-Torch#10]
Hi, 
very thankful to your released code, it helps me a lot!
I have tried running on my own dataset. 
If the image size is 3x32x32, all things go well.
However, when I set image size to 3x64x64, I got the error **"/usr/local/bin/luajit: bad argument #2 to '?' (out of range at /root/torch/pkg/torch/generic/Tensor.c:913)"**
Could you please help me with this problem?

**Comment by jwyang** [comment]
Hi, thanks,

I think that is because you did not change the network architecture, which still take 32x32 images as inputs. You need to define your own network architecture to train the model on images with size 64x64.

**Comment by r05922121** [comment]
Hi, thanks for reply!
Therefore, I should change it in models_def, right?

**Comment by jwyang** [comment]
yes, exactly.

**Comment by r05922121** [comment]
OK, I will close it, thanks!

**Comment by VeLKerr** [comment]
Hi, @jwyang ,
Could you please advice the architecture for clustering CIFAR-10?

**Comment by jwyang** [comment]
hi, @VeLKerr ,

you can use any architecture that could take 32x32 images as input. if you want, you can use the architecture for FRGC dataset.

**Comment by VeLKerr** [comment]
Thank you for quick reply!
I've changed `nInputPlanes` from 3 to 4 (because having RGBA images) and training started.

**Comment by jwyang** [comment]
great!
