### ISSUE TITLE
The wrong about dependencies and the fault of running the code

### ISSUE THREAD

**Issue by zz-kuku** [jwyang/JULE-Torch#12]
Hello, I have two questions when I install the torch with ubuntu16.04.
1. Ubuntu 16.04 don't provide the libqt4-core & libqt4-gui in the origin package, so when I run the command 
`curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash`
I failed and do not know whether it is affect the next steps.

2. When I skip the first step, and accomplish all the install steps. I run the first test code.

`th train.lua -dataset USPS -eta 0.9`

then the fault as follows:

> /home/haichao/torch/distro-master/install/bin/luajit: ...torch/distro-master/install/share/lua/5.1/trepl/init.lua:3
> 89: module 'hdf5' not found:No LuaRocks module found for hdf5	no field package.preload['hdf5']
> 	no file '/home/haichao/.luarocks/share/lua/5.1/hdf5.lua'
> 	no file '/home/haichao/.luarocks/share/lua/5.1/hdf5/init.lua'
> 	no file '/home/haichao/torch/distro-master/install/share/lua/5.1/hdf5.lua'
> 	no file '/home/haichao/torch/distro-master/install/share/lua/5.1/hdf5/init.lua'
> 	no file './hdf5.lua'
> 	no file '/home/haichao/torch/distro-master/install/share/luajit-2.1.0-beta1/hdf5.lua'
> 	no file '/usr/local/share/lua/5.1/hdf5.lua'
> 	no file '/usr/local/share/lua/5.1/hdf5/init.lua'
> 	no file '/home/haichao/.luarocks/lib/lua/5.1/hdf5.so'
> 	no file '/home/haichao/torch/distro-master/install/lib/lua/5.1/hdf5.so'
> 	no file '/home/haichao/torch/distro-master/install/lib/hdf5.so'
> 	no file './hdf5.so'
> 	no file '/usr/local/lib/lua/5.1/hdf5.so'
> 	no file '/usr/local/lib/lua/5.1/loadall.so'

I remember I have installed the hdf5 in other folder, and I have configured the .bashrc . So are there any steps I need to do ?

**Comment by zz-kuku** [comment]
The seconde question I have solved, but I meet new fault when I run the same code
`th train.lua -dataset USPS -eta 0.9`

> /home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [64,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [65,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [66,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [67,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [68,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [69,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [70,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [71,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [72,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [73,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [74,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [75,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [76,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [77,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [78,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [79,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [80,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [81,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [82,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [83,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [84,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [85,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [86,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [87,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [88,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [89,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [90,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [91,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [92,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [93,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [94,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [99,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [100,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [101,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [102,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [103,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [104,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [105,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [106,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [107,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [108,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [109,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [110,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [111,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [112,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [113,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [114,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [115,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [116,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [117,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [118,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [119,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [120,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [121,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [122,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [123,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed./home/haichao/torch/distro-master/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeI
> ndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [96,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.THCudaCheck FAIL file=/home/haichao/torch/distro-master/extra/cutorch/lib/THC/generic/THCTensorCopy.c
>  line=18 error=59 : device-side assert triggered/home/haichao/torch/distro-master/install/bin/luajit: train.lua:384: cuda runtime error (59) : device
> -side assert triggered at /home/haichao/torch/distro-master/extra/cutorch/lib/THC/generic/THCTensorCopy.c:18stack traceback:
> 	[C]: in function 'indexCopy'
> 	train.lua:384: in function 'organize_samples'
> 	train.lua:425: in function 'opfunc'
> 	.../torch/distro-master/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
> 	train.lua:439: in function 'updateCNN'
> 	train.lua:490: in main chunk
> 	[C]: in function 'dofile'
> 	...tro-master/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> 	[C]: at 0x00405d50


Are all these because the install of the dependencies ?

**Comment by jwyang** [comment]
Hi, regarding the last error, did you use a previous train.lua for training? It is shown that line 384 _indexCopy_ has some faults. However, the recent train.lua has _return_ . There is a small bug in function organize_samples in previous train.lua, which has been solved.

**Comment by zz-kuku** [comment]
@jwyang Thank you very much ! It is helpful to solve my question !
