### ISSUE TITLE
How to get the clustered data after training? 

### ISSUE THREAD

**Issue by Paper99** [jwyang/JULE-Torch#13]
Many Thanks for your code.
And I still have a question that HOW TO GET THE CLUSTERED DATA AFTER TRAINING.

**Comment by jwyang** [comment]
Hi, You will get the predicted label at the ending, and also learned representation:

Line 454-456 for saving predicted labels, and line 299-301 for saving learned representations.

**Comment by Paper99** [comment]
Thank you a lot.

**Comment by VeLKerr** [comment]
Hi, @jwyang, thanks a lot for the explanation above.

I've retrieved labels of each 20 epochs and feature matrices of last (100th) epoch. But I need to find out **the cluster of each image**. How I can correlate resulting labels and input images? Can we be sure that labels[0] corresponds to `0_cat.png` (the 1st image in CIFAR-10)?
