### ISSUE TITLE
It is difficult to train in Large dataset.

### ISSUE THREAD

**Issue by Paper99** [jwyang/JULE-Torch#14]
I use 80000 samples to train the jointed net.  But when I finished the first CNN update, it is difficult to run the next step. This code seemly have a large amount of computation in computing the 'Affinity',
How can I solve this problem?

**Comment by jwyang** [comment]
Hi, yes, it needs a lot of computation to update the affinity. I think one
way to address this problem is you can just compute a partial affinity
matrix, instead of a full affinity matrix.

**Comment by Paper99** [comment]
Thanks for your advice. 
And then I compute the partial affinity matrix, while I split the "NNs" matrix to 500*nclusters(4000+ in my samples) per batch. 
But computing the Affinity Matrix is still time-costing.

**Comment by Paper99** [comment]
Thanks for your advice.
I attempt to compute a partial affinity by spliting NNs to batch like you did in batch knn. But I failed. Because NMI for MNIST-test is much lower than before.
So how can I correctly get the partial affinity.

**Comment by jwyang** [comment]
Hi, I think one way to solve this is using some fast knn algorithm to build connections for close samples, and then compute the affinity for these close samples.
