### ISSUE TITLE
class torch.LongTensor cannot be indexed, cvt2TabelLabels error 

### ISSUE THREAD

**Issue by shaystrong** [jwyang/JULE-Torch#17]
I'm having trouble getting my custom data formatted into an appropriate hdf5 file, per your description. I manage to create the hdf5 file but I think I am having trouble with the 'labels' component of the hdf5 file: 

```train.lua:104: the class torch.LongTensor cannot be indexed
stack traceback:

/home/ec2-user/distro/install/bin/luajit: train.lua:104: the class torch.LongTensor cannot be indexed
stack traceback:
	[C]: in function '__newindex'
	train.lua:104: in function 'cvt2TabelLabels'
	train.lua:162: in main chunk
	[C]: in function 'dofile'
	...ser/distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x004064c0
```

In general I have a writer like this (where the labels are dummies for now for demonstration purposes): 

```import h5py
import glob
import os.path
import time
from PIL import Image
import tempfile
import numpy as np

ims = [np.array(Image.open(f)) for f in glob.glob('*.jpg')]

def setup_hdf5_file(shape, name, **options):
    f = h5py.File(name+'.h5', 'w')
    f.create_dataset('data', shape, **options)
    f.create_dataset('labels', (len(ims),1), **options)
    return f

def save_images(f):
    for i, im in enumerate(ims):
        f['data'][i,...] = im.T
        f['labels'][i,...] = int(1)
    f.close()

def benchmark(name, **options):
    tstart = time.time()
    f = setup_hdf5_file((len(ims),3,256, 256), name, **options)
    save_images(f)
    tstop = time.time()
    size = os.path.getsize(name+'.h5')
    print("{0}: {1:.1f}s, {2}MB".format(name, tstop-tstart, size//1e6))


benchmark('data4torch')
```

it is not clear to me what format may be expected for the 'labels' (also are they even needed given the context of your use case? You don't mention this in the readme.

**Comment by jwyang** [comment]
Hi, 

The order of "labels" should be 1, say you have N samples, then it should be N, instead of N x 1.

You are right that the gt labels will not be used during the training, but will be used during the evaluation, i.e., computing the NMI. If you do not have the ground truth labels, then that's fine, you just randomly initialize it, and then manually set the target number of clusters at line:

163: target_nclusters_table[i] = #(label_gt_table_table[I])


Hope this will resolve your issue.

**Comment by shaystrong** [comment]
brilliant! thank you! I had tried that originally, but used

```
...
    f.create_dataset('labels', (len(ims)), **options)
```

which throws errors. The fix is below. Now it is running. I appreciate your help! I'm super excited about this code!

```def setup_hdf5_file(shape, name, **options):
    f = h5py.File(name+'.h5', 'w')
    f.create_dataset('data', shape, **options)
    f.create_dataset('labels', (len(ims),), **options)
    return f

def save_images(f):
    for i, im in enumerate(ims):
        f['data'][i,...] = im.T
        f['labels'][i] = np.random.randint(500)
    f.close()

def benchmark(name, **options):
    tstart = time.time()
    f = setup_hdf5_file((len(ims),3,256, 256), name, **options)
    save_images(f)
    tstop = time.time()
    size = os.path.getsize(name+'.h5')
    print("{0}: {1:.1f}s, {2}MB".format(name, tstop-tstart, size//1e6))


benchmark('data4torch')
```

**Comment by jwyang** [comment]
Great! Hope the code is useful to you, -:)
