### ISSUE TITLE
Can I run this code If my data have no label? 

### ISSUE THREAD

**Issue by zuoeye** [jwyang/JULE-Torch#18]
Is this code directed against unlabeled data? Why the data in the example have label?  Can I run this code If my data have no label?

**Comment by jwyang** [comment]
yes, you can, replace the labels with any numbers and then run the algorithm. In this case, you just get some meaningless evaluation results.

**Comment by zuoeye** [comment]
Do the numbers that I set affect the result？Do different sets have different results？Do I need to set the same category to the same number？ 
发自网易邮箱大师
On 11/28/2017 10:44, Jianwei Yang wrote: yes, you can, replace the labels with any numbers and then run the algorithm. In this case, you just get some meaningless evaluation results.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jwyang/JULE-Torch","title":"jwyang/JULE-Torch","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jwyang/JULE-Torch"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jwyang in #18: yes, you can, replace the labels with any numbers and then run the algorithm. In this case, you just get some meaningless evaluation results."}],"action":{"name":"View Issue","url":"https://github.com/jwyang/JULE-Torch/issues/18#issuecomment-347396240"}}}

**Comment by jwyang** [comment]
Do the numbers that I set affect the result？

no, it will not affect the results

Do different sets have different results？

no, 

Do I need to set the same category to the same number？

no, just randomly set the ground truth labels.

**Comment by zuoeye** [comment]
Thanks for your advice.
And I am having trouble when run my data:
`==> testing    
NMI:     nan    
==> online epoch # 0 [batchSize = 100] [learningRate = 0.01]    
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-3009/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/home/ai/torch/install/bin/luajit: /home/ai/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 2 module of nn.Sequential:
In 1 module of nn.Sequential:
In 2 module of nn.Sequential:
/home/ai/torch/install/share/lua/5.1/nn/THNN.lua:110: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-3009/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
    [C]: in function 'v'
    /home/ai/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'BatchNormalization_updateOutput'
    ...ai/torch/install/share/lua/5.1/nn/BatchNormalization.lua:124: in function <...ai/torch/install/share/lua/5.1/nn/BatchNormalization.lua:113>
    [C]: in function 'xpcall'
    /home/ai/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:41>
    [C]: in function 'xpcall'
    /home/ai/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:41>
    [C]: in function 'xpcall'
    /home/ai/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
    train.lua:421: in function 'opfunc'
    /home/ai/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
    train.lua:436: in function 'updateCNN'
    train.lua:487: in main chunk
    [C]: in function 'dofile'
    ...e/ai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
    [C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
    [C]: in function 'error'
    /home/ai/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
    /home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
    train.lua:421: in function 'opfunc'
    /home/ai/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
    train.lua:436: in function 'updateCNN'
    train.lua:487: in main chunk
    [C]: in function 'dofile'
    ...e/ai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
    [C]: at 0x00406670`
How to solve this problem?

**Comment by zuoeye** [comment]
`==> testing    
NMI:     nan    
==> online epoch # 0 [batchSize = 100] [learningRate = 0.01]    
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-3009/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/home/ai/torch/install/bin/luajit: /home/ai/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 2 module of nn.Sequential:
In 1 module of nn.Sequential:
In 2 module of nn.Sequential:
/home/ai/torch/install/share/lua/5.1/nn/THNN.lua:110: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-3009/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
    [C]: in function 'v'
    /home/ai/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'BatchNormalization_updateOutput'
    ...ai/torch/install/share/lua/5.1/nn/BatchNormalization.lua:124: in function <...ai/torch/install/share/lua/5.1/nn/BatchNormalization.lua:113>
    [C]: in function 'xpcall'
    /home/ai/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:41>
    [C]: in function 'xpcall'
    /home/ai/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:41>
    [C]: in function 'xpcall'
    /home/ai/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
    train.lua:421: in function 'opfunc'
    /home/ai/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
    train.lua:436: in function 'updateCNN'
    train.lua:487: in main chunk
    [C]: in function 'dofile'
    ...e/ai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
    [C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
    [C]: in function 'error'
    /home/ai/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
    /home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
    train.lua:421: in function 'opfunc'
    /home/ai/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
    train.lua:436: in function 'updateCNN'
    train.lua:487: in main chunk
    [C]: in function 'dofile'
    ...e/ai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
    [C]: at 0x00406670
`

**Comment by zuoeye** [comment]
` NMI:     nan    
==> online epoch # 0 [batchSize = 100] [learningRate = 0.01]    
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-3009/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/home/ai/torch/install/bin/luajit: /home/ai/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 2 module of nn.Sequential:
In 1 module of nn.Sequential:
In 2 module of nn.Sequential:
/home/ai/torch/install/share/lua/5.1/nn/THNN.lua:110: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-3009/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
    [C]: in function 'v'
    /home/ai/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'BatchNormalization_updateOutput'
    ...ai/torch/install/share/lua/5.1/nn/BatchNormalization.lua:124: in function <...ai/torch/install/share/lua/5.1/nn/BatchNormalization.lua:113>
    [C]: in function 'xpcall'
    /home/ai/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:41>
    [C]: in function 'xpcall'
    /home/ai/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:41>
    [C]: in function 'xpcall'
    /home/ai/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
    train.lua:421: in function 'opfunc'
    /home/ai/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
    train.lua:436: in function 'updateCNN'
    train.lua:487: in main chunk
    [C]: in function 'dofile'
    ...e/ai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
    [C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
    [C]: in function 'error'
    /home/ai/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
    /home/ai/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
    train.lua:421: in function 'opfunc'
    /home/ai/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
    train.lua:436: in function 'updateCNN'
    train.lua:487: in main chunk
    [C]: in function 'dofile'
    ...e/ai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
    [C]: at 0x00406670`

**Comment by jwyang** [comment]
it seems that it is out of memory. How much GPU memory do you have? Which GPU are you using? Did you run the examples in this repo, such as MNIST-test, USPS, etc?

**Comment by zuoeye** [comment]
I think the labels can effect the result. The result was different when I used different labels.

**Comment by jwyang** [comment]
you mean the NMI evaluation results? It will definitely affect these results. Also, since the CNN is randomly initialized. Each run you will have slightly different results as well.
