### ISSUE TITLE
how to calculate diff in loss layer

### ISSUE THREAD

**Issue by xiaoyuliu** [jwyang/JULE-Torch#2]
Hi,

I tried to implement the loss layer using python you mentioned in the paper (eq(11)), however I have no idea how the diff should look like, because usually there will  be three diffs for anchors/positives/negatives. Can you please provide the sample using only feats and labels as inputs?

Thanks!

**Comment by jwyang** [comment]
Hi, @codingsmallfish 

At line 429 in train.lua, I used organize_samples() function to organize triplets given the feats and labels. The outputs are triplet and triplet index for eq(11). You can take the function organize_samples function as a reference if you plan to reimplement by python.

please let me know if you have concerns.

thanks,
Jianwei

**Comment by codingsmallfish** [comment]
Hi, @jwyang 

Thank you pretty much!
