### ISSUE TITLE
"bad argument #2 to '?'" error on CIFAR dataset

### ISSUE THREAD

**Issue by VeLKerr** [jwyang/JULE-Torch#21]
Hi, 

I'm trying to learn clustering on CIFAR-10 dataset. As a feature extraction model I'm using FRGC's model with minimal changes:
* `nInputLayers[0]` incrreased to 4 because I have RGBA images,
* the size of chunks have been saved in `local chunkSizes = {5, 5}` because I'm planning to change the size for each layer separately. So I'm using convolutional NN as following: 
`module:add(backend.SpatialConvolution(nInputPlane, nOutputPlane, chunkSize, chunkSize, 1, 1, 0, 0))`

But I'm catching the error: 
```
[torch.LongStorage of size 2]

sigma: 	0	
/home/velkerr/PHd/libs/torch/install/bin/luajit: bad argument #2 to '?' (out of range at /home/velkerr/PHd/libs/torch/pkg/torch/generic/Tensor.c:704)
stack traceback:
	[C]: at 0x7f0a0f314580
	[C]: in function '__newindex'
	./affinity/affinity.lua:39: in function 'compute'
	train.lua:201: in function 'updateLabels'
	train.lua:284: in function 'merge_label'
	train.lua:482: in main chunk
	[C]: in function 'dofile'
	...libs/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d00
```
As I understood, the error caused by too small dataset or too large batch size. I've experimented with different batchSizes (500, 100, 50) but I'm still seeing this error. 

What I'm doing wrong? Thank you for help in advance.

**Comment by jwyang** [comment]
it seems that the index is out of range at line 39. How many samples did you use to train? it might because sample < k+1

**Comment by VeLKerr** [comment]
Have I understood correctly that by "sample" you meant "number of negative samples" i.e. `num_nsampling`? 
I'm using `num_sampling = 20` and `K_s = 20` (default values). Looks like in my case the inequality was satisfied: 
```
num_sampling < K_s + 1
```
Anyway thank you very much for the help, I'll experiment with decreased `num_sampling`.

**Comment by jwyang** [comment]
no, no, it does not satisfy, you need 

number of sample > k+1

**Comment by VeLKerr** [comment]
Thank you, I've understood it and increased the number of sampling.

However it's interesting why I wasn't encounter such error on MNIST (both parts) and FRGC dataset...
