### ISSUE TITLE
parameters set 

### ISSUE THREAD

**Issue by frankwanL** [jwyang/JULE-Torch#5]
hi,
   I have run your code successfully! now, I want to know how to set the target number of clusters,  the initial image labels and CNN parameters.
thank you!

**Comment by jwyang** [comment]
Hi, great,

In my code, the target number of clusters is equal to the groundtruth number of clusters in the dataset. I used _target_nclusters_table_ to store the target numbers of clusters, and it is initialized at line 163 in train.lua,  you may change that.

The initial image labels are obtained by running: label_pre = agg_clustering.init(ind) at line 205 in train.lua. It is simply find samples along the nearest neighbor chain.

In terms of CNN parameters, they are all randomly initialized using the function NetInit(net) at line 79 in train.lua.

Please let me know if you have any further issues.

**Comment by frankwanL** [comment]
I try to train my own dataset, but when the program run to the place calculate the loss at, it stop.

**Comment by jwyang** [comment]
what does 'stop' mean? just stuck or some errors occur?

**Comment by frankwanL** [comment]
stuck,as follow.
==> online epoch # 1 [batchSize = 100] [learningRate = 0.009946337969733]	
loss: 	0.10467874380258	
loss: 	0.11827562772311	
loss: 	1.4975162120348	
loss: 	32.990916700487	
loss: 	0.1337756290614	
loss: 	0.10189099246508	
loss: 	37.9046875

**Comment by frankwanL** [comment]
as follows,
/home/wl/torch/install/bin/luajit: bad argument #2 to '?' (out of range at /home/wl/torch/pkg/torch/generic/Tensor.c:890)
stack traceback:
	[C]: at 0x7f6b5d63c2d0
	[C]: in function '__index'
	train.lua:370: in function 'organize_samples'
	train.lua:429: in function 'opfunc'
	/home/wl/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
	train.lua:443: in function 'updateCNN'
	train.lua:494: in main chunk
	[C]: in function 'dofile'
	...e/wl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by frankwanL** [comment]
/home/wl/torch/install/bin/luajit: cannot open models_def/MYDATASET.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	train.lua:146: in main chunk
	[C]: in function 'dofile'
	...e/wl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by frankwanL** [comment]
I make a new folder named 'MyDataset' in datasets and put data4torch.h5 into it, then run the command 'th train.lua -dataset MyDataset -eta 0.9', then it show:
torch/install/bin/luajit: cannot open models_def/MyDataset.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	train.lua:146: in main chunk
	[C]: in function 'dofile'
	...e/wl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by jwyang** [comment]
Hi,

you should also create a model file to define the network architecture for your dataset
